databases:
  - name: smile
    databaseName: smile
    user: smile_user

services:
  - type: web
    name: ticket
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ticket
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false